import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const indexHtml = readFileSync(join(__dirname, "..", "index.html"), "utf8");
const faviconSvg = readFileSync(join(__dirname, "..", "favicon.svg"), "utf8");

assert.match(indexHtml, /\.grid\s*{[^}]*grid-template-columns: minmax\(0, 1\.15fr\) minmax\(360px, 0\.85fr\);/s);
assert.match(indexHtml, /\.workspace-column\s*{[^}]*min-width: 0;[^}]*align-content: start;/s);
assert.match(indexHtml, /\.sections-panel\s*{[^}]*grid-template-rows: auto minmax\(0, 1fr\);[^}]*max-height: var\(--player-panel-height, none\);[^}]*overflow: hidden;/s);
assert.match(indexHtml, /\.section-list\s*{[^}]*overflow-y: auto;/s);
assert.match(indexHtml, /@media \(max-width: 980px\)[\s\S]*?grid-template-areas:\s*"player"\s*"sections"\s*"fine"\s*"support";[\s\S]*?\.workspace-column\s*{[^}]*display: contents;[\s\S]*?\.player-panel\s*{[^}]*grid-area: player;[\s\S]*?\.sections-panel\s*{[^}]*grid-area: sections;[\s\S]*?\.fine-panel\s*{[^}]*grid-area: fine;[\s\S]*?\.supporting-panels\s*{[^}]*grid-area: support;/);
assert.match(indexHtml, /@media \(max-width: 980px\)[\s\S]*?\.sections-panel\s*{[^}]*max-height: none;[^}]*overflow: visible;/);
assert.match(indexHtml, /h2,\s*h3\s*{[^}]*margin: 0;/s);
assert.match(indexHtml, /header,\s*main\s*{[^}]*width: min\(1240px, calc\(100% - 2rem\)\);/s);
assert.match(indexHtml, /h1\s*{[^}]*margin: 0;[^}]*font-size: clamp\(2rem, 4vw, 3\.8rem\);/s);
assert.match(indexHtml, /\.panel p\s*{[^}]*margin: 0;/s);
assert.match(indexHtml, /\.fine-header,\s*\.fine-row\s*{[^}]*display: flex;[^}]*justify-content: space-between;/s);
assert.match(indexHtml, /\.nudge-amount-buttons button\[aria-pressed="true"\]\s*{[^}]*border-color: var\(--accent\);/s);
assert.match(indexHtml, /\.fine-grid\s*{[^}]*display: grid;[^}]*gap: 0\.65rem;/s);
assert.match(indexHtml, /\.section-fields\s*{[^}]*grid-template-columns: minmax\(0, 1fr\);/s);
assert.match(indexHtml, /\.time-input-actions\s*{[^}]*display: flex;[^}]*flex-wrap: wrap;[^}]*min-width: 0;/s);
assert.match(indexHtml, /\.time-input-actions > \[data-action\^="seek-to-"\]\s*{[^}]*margin-left: auto;/s);
assert.match(indexHtml, /--time-input-width: 10rem;/);
assert.match(indexHtml, /\.time-input-wrap\s*{[^}]*grid-template-columns: var\(--time-input-width\) minmax\(0, 1fr\);/s);
assert.match(indexHtml, /\.time-input-wrap input\[data-time-input="true"\]\s*{[^}]*width: var\(--time-input-width\);/s);
assert.match(indexHtml, /@media \(max-width: 680px\)[\s\S]*?\.time-input-wrap\s*{[^}]*grid-template-columns: minmax\(0, 1fr\);/);
assert.match(indexHtml, /\.current-time-block\s*{[^}]*flex: 1 1 0;[^}]*min-width: 0;/s);
assert.match(indexHtml, /\.active-section-block\s*{[^}]*flex: 0 0 12rem;[^}]*min-width: 0;[^}]*max-width: 100%;[^}]*margin-left: auto;/s);
assert.match(indexHtml, /\.active-section-select\s*{[^}]*width: 100%;/s);
assert.match(indexHtml, /\.section-end-options\s*{[^}]*display: flex;[^}]*align-items: center;[^}]*flex-wrap: wrap;[^}]*flex: 1 0 100%;/s);
assert.match(indexHtml, /@media \(max-width: 680px\)[\s\S]*?\.current-time-block\s*{[^}]*flex-basis: 100%;[^}]*min-width: 0;/);
assert.match(indexHtml, /\.status\s*{[^}]*min-height: 1\.35rem;/s);
assert.match(indexHtml, /#videoStatus:empty,\s*#shareStatus:empty\s*{[^}]*display: none;/s);
assert.match(indexHtml, /\.video-load-row\s*{[^}]*flex-wrap: nowrap;/s);
assert.match(indexHtml, /\.video-load-row > \.grow\s*{[^}]*flex: 1 1 0;[^}]*min-width: 0;/s);
assert.match(indexHtml, /\.video-load-row > button\s*{[^}]*flex: 0 0 auto;/s);
assert.match(indexHtml, /@media \(max-width: 680px\)[\s\S]*?\.video-load-row > \.grow\s*{[^}]*flex-basis: 0;/);
assert.match(indexHtml, /\.share-url-row\s*{[^}]*flex-wrap: nowrap;/s);
assert.match(indexHtml, /\.row\.share-url-row > textarea\s*{[^}]*flex: 1 1 0;[^}]*min-width: 0;/s);
assert.match(indexHtml, /\.row\.share-url-row > button\s*{[^}]*flex: 0 0 auto;/s);
assert.match(indexHtml, /<link rel="icon" href="favicon\.svg" type="image\/svg\+xml">/);
assert.match(faviconSvg, /<rect[^>]*fill="#0f172a"/);
assert.match(faviconSvg, /<path[^>]*fill="#fff"/);

assert.match(indexHtml, /id="playerPanel"[^>]*player-panel/);
assert.match(indexHtml, /id="sectionsPanel"[^>]*sections-panel/);
assert.match(indexHtml, /<div class="time-readout">\s*<div class="current-time-block">[\s\S]*?<div class="current-time-row">[\s\S]*?<button id="playPauseButton"[^>]*>Play \/ Pause<\/button>[\s\S]*?<\/div>\s*<\/div>\s*<div class="active-section-block">[\s\S]*?<select id="activeSectionSelect"[\s\S]*?<\/select>\s*<\/div>\s*<div class="section-end-options"[^>]*aria-label="Playback options">[\s\S]*?<input id="loopToggle"[^>]*checked>[\s\S]*?Loop active section[\s\S]*?<input id="useSectionSpeedToggle" type="checkbox" checked>[\s\S]*?Use section speed[\s\S]*?<input id="moveToNextSectionToggle" type="checkbox">[\s\S]*?Move to next section/);
assert.match(indexHtml, /<div class="row video-load-row">\s*<input id="videoInput"[^>]*>\s*<input id="videoTitleInput"[^>]*aria-label="YouTube title"[^>]*maxlength="200"[^>]*hidden>\s*<button id="loadVideoButton"[^>]*>Load video<\/button>\s*<\/div>/);
assert.doesNotMatch(indexHtml, /seekBackButton|seekForwardButton|[−+]5s/);
assert.match(indexHtml, /<label for="activeSectionSelect">Active section<\/label>\s*<select id="activeSectionSelect"[^>]*>\s*<option value="-1">None<\/option>/);
assert.doesNotMatch(indexHtml, /activeSectionLabel|renderActiveLabel|active-badge/);
assert.match(indexHtml, /<div class="stack workspace-column player-column">[\s\S]*?<section id="playerPanel"[\s\S]*?<aside class="stack supporting-panels"[\s\S]*?<\/aside>\s*<\/div>\s*<div class="stack workspace-column sections-column">/);
assert.match(indexHtml, /<div class="stack workspace-column sections-column">[\s\S]*?<section id="sectionsPanel"[\s\S]*?<\/section>\s*<section id="fineTunePanel" class="panel stack fine-panel"[^>]*hidden>[\s\S]*?<\/section>\s*<\/div>/);
assert.match(indexHtml, /<header>\s*<h1>YouTube Practice Sections<\/h1>\s*<\/header>\s*<main class="grid">/);
assert.doesNotMatch(indexHtml, /class="subtitle"/);
assert.doesNotMatch(indexHtml, /Expand a section to edit it|Select a section, choose start or end|seekActiveStartButton|function seekActiveStart\b/);
assert.match(indexHtml, /<h2 id="sectionsHeading">Sections<\/h2>[\s\S]*?<button id="addSectionButton"[^>]*>Add section<\/button>/);
assert.doesNotMatch(indexHtml, /Practice sections|Add section at playhead/);
assert.match(indexHtml, /<div class="field">\s*<label for="shareUrl">Current share URL<\/label>\s*<div class="row share-url-row">\s*<textarea id="shareUrl" readonly spellcheck="false"><\/textarea>\s*<button id="copyShareButton"[^>]*>Copy URL<\/button>\s*<\/div>\s*<\/div>\s*<output id="shareStatus"/);
assert.doesNotMatch(indexHtml, /Share \/ Export|shareHint|newUrlButton|openNewUrl|>New URL<|id="(?:openShareButton|resetButton)"|>Open URL<|>Reset page state</);
assert.match(indexHtml, /<div class="fine-row" role="group" aria-label="Adjust section start">[\s\S]*?id="nudgeStartDownButton"[\s\S]*?id="nudgeStartUpButton"/);
assert.match(indexHtml, /<div class="fine-row" role="group" aria-label="Adjust section end">[\s\S]*?id="nudgeEndDownButton"[\s\S]*?id="nudgeEndUpButton"/);
assert.match(indexHtml, /id="fineTunePanel"[^>]*aria-describedby="fineTuneHint"/);
const fineTuneHint = indexHtml.match(/<p id="fineTuneHint" class="hint">([\s\S]*?)<\/p>/)?.[1] || "";
assert.match(fineTuneHint, /<kbd>,<\/kbd> \/ <kbd>\.<\/kbd>/);
const fineTuneAmountHint = fineTuneHint.match(/<span class="fine-tune-amount-hint">([\s\S]*?)<\/span>/)?.[1] || "";
assert.equal(fineTuneAmountHint.replace(/<[^>]+>/g, "").trim(), "Press - / + to decrease / increase the amount.");
assert.match(indexHtml, /\.fine-tune-amount-hint\s*{[^}]*display: block;[^}]*margin-top: 0\.35rem;/s);
assert.match(indexHtml, /<div id="nudgeAmountButtons" class="nudge-amount-buttons" role="group" aria-label="Fine tune amount">\s*<button[^>]*data-nudge-amount="0\.05" aria-pressed="false">0\.05s<\/button>\s*<button[^>]*data-nudge-amount="0\.1" aria-pressed="true">0\.1s<\/button>\s*<button[^>]*data-nudge-amount="0\.25" aria-pressed="false">0\.25s<\/button>\s*<button[^>]*data-nudge-amount="0\.5" aria-pressed="false">0\.5s<\/button>\s*<button[^>]*data-nudge-amount="1" aria-pressed="false">1s<\/button>\s*<\/div>/);
assert.doesNotMatch(indexHtml, /id="fineTarget"|id="nudgeAmount"|<option value="playhead"|<label[^>]*>\s*(?:Target|Nudge amount)\s*<\/label>/);
assert.match(indexHtml, /const NUDGE_AMOUNTS = \[0\.05, 0\.1, 0\.25, 0\.5, 1\];\s*const DEFAULT_NUDGE_AMOUNT = 0\.1;[\s\S]*?let selectedNudgeAmount = DEFAULT_NUDGE_AMOUNT;/);
assert.match(indexHtml, /function getNudgeAmount\(\)\s*{\s*return selectedNudgeAmount;/);
assert.match(indexHtml, /function setNudgeAmount\(value\)[\s\S]*?NUDGE_AMOUNTS\.includes\(amount\)[\s\S]*?setAttribute\("aria-pressed"/);
assert.match(indexHtml, /function stepNudgeAmount\(direction\)[\s\S]*?direction !== -1 && direction !== 1[\s\S]*?Math\.min\(NUDGE_AMOUNTS\.length - 1, Math\.max\(0, currentIndex \+ direction\)\)[\s\S]*?setNudgeAmount\(NUDGE_AMOUNTS\[nextIndex\]\);/);
assert.match(indexHtml, /elements\.nudgeAmountButtons\.addEventListener\("click"[\s\S]*?button\[data-nudge-amount\][\s\S]*?setNudgeAmount\(button\.dataset\.nudgeAmount\);/);
assert.match(indexHtml, /function nudgeSelected\(target, delta\)\s*{\s*if \(!\["start", "end"\]\.includes\(target\)\) return;/);
assert.match(indexHtml, /function nudgeTimeInput\(input, delta\)[\s\S]*?updateSectionTime\(index, field, section\[field\] \+ delta, { render: false }\);[\s\S]*?updateSectionTimeDisplay\(index\);[\s\S]*?syncUrl\(\);/);
assert.match(indexHtml, /function updateSectionTimeDisplay\(index, options = {}\)[\s\S]*?input !== options\.preserveInput[\s\S]*?\.section-summary-time/);
assert.match(indexHtml, /if \(Number\.isFinite\(parsed\)\)\s*{\s*updateSectionTime\(index, field, parsed, { render: false }\);\s*updateSectionTimeDisplay\(index, { preserveInput: target }\);\s*syncUrl\(\);/);
assert.match(indexHtml, /\(key === "," \|\| key === "\."\) && isSectionTimeInput\(event\.target\)[\s\S]*?nudgeTimeInput\(event\.target, \(key === "," \? -1 : 1\) \* getNudgeAmount\(\)\);/);
assert.match(indexHtml, /const decreasesAmount = key === "-" \|\| key === "_";\s*const increasesAmount = key === "=" \|\| key === "\+";[\s\S]*?if \(decreasesAmount \|\| increasesAmount\)[\s\S]*?event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey[\s\S]*?elements\.fineTunePanel\.hidden[\s\S]*?isTypingTarget\(event\.target\) && !isSectionTimeInput\(event\.target\)[\s\S]*?stepNudgeAmount\(decreasesAmount \? -1 : 1\);/);
assert.match(indexHtml, /function isTypingTarget\(target\)[\s\S]*?\["INPUT", "TEXTAREA", "SELECT"\][\s\S]*?target\.isContentEditable/);
assert.doesNotMatch(indexHtml, /<li><kbd>[,.]<\/kbd>\s*Seek|else if \(key === "[,.]"\)|function seekBy\b/);
assert.match(indexHtml, /if \(action === "play-section"\)\s*{\s*playSection\(index\);\s*return;/);
assert.match(indexHtml, /function playSection\(index = state\.activeIndex\)[\s\S]*?state\.loop = true;[\s\S]*?syncAndRender\(\);/);
assert.match(indexHtml, /else if \(key === "p"\)[\s\S]*?playSection\(\);/);
assert.match(indexHtml, /moveToNextSectionToggle: document\.getElementById\("moveToNextSectionToggle"\)/);
assert.match(indexHtml, /elements\.moveToNextSectionToggle\.addEventListener\("change"[\s\S]*?state\.moveToNextSection = elements\.moveToNextSectionToggle\.checked;/);
assert.match(indexHtml, /useSectionSpeedToggle: document\.getElementById\("useSectionSpeedToggle"\)/);
assert.match(indexHtml, /elements\.useSectionSpeedToggle\.addEventListener\("change"[\s\S]*?state\.useSectionSpeed = elements\.useSectionSpeedToggle\.checked;\s*applyActiveSpeed\(\);\s*syncAndRender\(\);/);
assert.match(indexHtml, /state\.moveToNextSection = normalized\.moveToNextSection;/);
assert.match(indexHtml, /state\.useSectionSpeed = normalized\.useSectionSpeed;/);
assert.match(indexHtml, /elements\.moveToNextSectionToggle\.checked = state\.moveToNextSection;/);
assert.ok((indexHtml.match(/elements\.useSectionSpeedToggle\.checked = state\.useSectionSpeed;/g) || []).length >= 2, "speed checkbox should refresh during state application and rendering");
assert.match(indexHtml, /function updateSectionSpeed\(index, value\)[\s\S]*?section\.speed = roundSpeed\(value\);\s*state\.useSectionSpeed = true;\s*elements\.useSectionSpeedToggle\.checked = true;\s*applyActiveSpeed\(\);\s*syncUrl\(\);/);
assert.match(indexHtml, /function applyActiveSpeed\(\)[\s\S]*?if \(!state\.useSectionSpeed \|\| !section\)\s*{\s*player\.setPlaybackRate\(1\);\s*return;[\s\S]*?nearestNumber\(available, desired\)/);
assert.match(indexHtml, /videoTitleInput: document\.getElementById\("videoTitleInput"\)/);
assert.match(indexHtml, /elements\.videoTitleInput\.addEventListener\("input", handleVideoTitleInput\);/);
assert.match(indexHtml, /state\.videoTitle = normalized\.videoTitle;[\s\S]*?pendingVideoTitleId = state\.videoId && !state\.videoTitle \? state\.videoId : "";/);
assert.match(indexHtml, /function renderVideoTitle\(\)\s*{\s*elements\.videoTitleInput\.hidden = !state\.videoId;\s*elements\.videoTitleInput\.value = state\.videoTitle;\s*updateDocumentTitle\(\);/);
assert.match(indexHtml, /function updateDocumentTitle\(\)\s*{\s*document\.title = state\.videoTitle \? `\$\{APP_TITLE}: \$\{state\.videoTitle}` : APP_TITLE;/);
assert.match(indexHtml, /function captureVideoTitleFromPlayer\(\)[\s\S]*?!pendingVideoTitleId \|\| state\.videoTitle[\s\S]*?videoId !== pendingVideoTitleId \|\| videoId !== state\.videoId[\s\S]*?state\.videoTitle = videoTitle;[\s\S]*?syncUrl\(\);/);
assert.match(indexHtml, /if \(videoId !== state\.videoId\) state\.videoTitle = "";\s*state\.videoId = videoId;\s*pendingVideoTitleId = state\.videoTitle \? "" : videoId;/);
assert.ok((indexHtml.match(/captureVideoTitleFromPlayer\(\);/g) || []).length >= 3, "player loading and lifecycle events should try to capture missing titles");
assert.match(indexHtml, /function renderAll\(\)\s*{\s*renderVideoTitle\(\);/);
assert.match(indexHtml, /if \(state\.moveToNextSection && nextSection\)[\s\S]*?state\.activeIndex \+= 1;[\s\S]*?syncAndRender\(\);[\s\S]*?else if \(state\.loop\)/);
assert.match(indexHtml, /activeSectionSelect: document\.getElementById\("activeSectionSelect"\)/);
assert.match(indexHtml, /elements\.activeSectionSelect\.addEventListener\("change", handleActiveSectionChange\);/);
assert.match(indexHtml, /function handleActiveSectionChange\(\)[\s\S]*?!!getActiveSection\(\) && isPlayerPlaying\(\);[\s\S]*?if \(wasPlayingActiveSection && Number\.isInteger\(index\) && state\.sections\[index\]\)[\s\S]*?playSection\(index\);[\s\S]*?selectSection\(index\);\s*syncAndRender\(\);/);
assert.match(indexHtml, /function formatSectionLabel\(section, index\)[\s\S]*?name \? `\$\{index \+ 1}\. \$\{name}` : `\$\{index \+ 1}\.`;/);
assert.match(indexHtml, /function renderActiveSectionSelect\(\)[\s\S]*?state\.sections\.map\(\(section, index\)[\s\S]*?escapeAttribute\(formatSectionLabel\(section, index\)\)[\s\S]*?elements\.activeSectionSelect\.value = String\(activeIndex\);/);
assert.ok((indexHtml.match(/renderActiveSectionSelect\(\)/g) || []).length >= 4, "active section select should refresh across render, name, and focus paths");
assert.match(indexHtml, /if \(field === "name"\)[\s\S]*?state\.sections\[index\]\.name = target\.value\.slice\(0, 120\);\s*updateSectionNameDisplay\(index\);\s*syncUrl\(\);\s*renderActiveSectionSelect\(\);/);
assert.match(indexHtml, /function updateSectionNameDisplay\(index\)[\s\S]*?\.section-summary-name[\s\S]*?summary\.textContent = formatSectionLabel\(section, index\);/);
assert.match(indexHtml, /function selectSection\(index\)[\s\S]*?guardSectionBoundary\(getActiveSection\(\)\);[\s\S]*?applyActiveSpeed\(\);/);
assert.match(indexHtml, /function guardSectionBoundary\(section, settleMs = 500\)[\s\S]*?Date\.now\(\) \+ settleMs/);
assert.match(indexHtml, /fineTunePanel: document\.getElementById\("fineTunePanel"\)/);
assert.match(indexHtml, /elements\.fineTunePanel\.hidden = !state\.sections\.some\(section => expandedSectionIds\.has\(section\.id\)\);/);
assert.match(indexHtml, /\.fine-panel\[hidden\]\s*{[^}]*display: none;/s);

assert.match(indexHtml, /data-action="toggle-section"[^>]*aria-expanded="\$\{expanded}"[^>]*aria-controls="\$\{detailsId}"/);
assert.match(indexHtml, /\.section-card\.collapsed\s*{[^}]*padding: 0\.45rem 0\.55rem;/s);
assert.match(indexHtml, /class="section-card \$\{expanded \? "expanded" : "collapsed"}/);
assert.match(indexHtml, /data-section-id="\$\{escapeAttribute\(section\.id\)}"/);
assert.match(indexHtml, /class="section-details"\$\{expanded \? "" : " hidden"}/);
assert.match(indexHtml, /class="section-summary-controls">[\s\S]*?data-field="speed"[\s\S]*?data-action="play-section"[^>]*>Play<\/button>\s*<\/div>\s*<\/div>\s*<div id="\$\{detailsId\}"/);
assert.match(indexHtml, /function renderTimeField\(section, index, field, label\)[\s\S]*?field === "start" && index > 0[\s\S]*?data-action="start-from-previous-section"[^>]*>Previous section<\/button>[\s\S]*?field === "end" && index < state\.sections\.length - 1[\s\S]*?data-action="end-from-next-section"[^>]*>Next section<\/button>/);
assert.match(indexHtml, /class="time-input-actions">\s*<button[^>]*data-action="set-\$\{field}-now"[^>]*>Now<\/button>\s*\$\{neighborButton}\s*<button[^>]*data-action="seek-to-\$\{field}"[^>]*>Go<\/button>/);
assert.match(indexHtml, /if \(action === "set-start-now"\) setSectionBoundaryToNow\(index, "start"\);\s*if \(action === "set-end-now"\) setSectionBoundaryToNow\(index, "end"\);\s*if \(action === "seek-to-start"\) seekTo\(state\.sections\[index\]\.start\);\s*if \(action === "seek-to-end"\) seekTo\(state\.sections\[index\]\.end\);/);
assert.match(indexHtml, /if \(action === "start-from-previous-section"\) copySectionBoundaryFromNeighbor\(state\.sections, index, "start"\);\s*if \(action === "end-from-next-section"\) copySectionBoundaryFromNeighbor\(state\.sections, index, "end"\);/);
assert.match(indexHtml, /<div class="section-actions">\s*<button class="primary small" data-action="insert-after"[^>]*>New section after<\/button>\s*<button class="danger small" data-action="delete"[^>]*>Delete<\/button>\s*<\/div>/);
assert.match(indexHtml, /\.section-actions > \[data-action="delete"\]\s*{[^}]*margin-left: auto;/s);
assert.match(indexHtml, /if \(action === "delete"\)\s*{\s*deleteSection\(index\);\s*syncAndRender\(\);\s*return;/);
assert.match(indexHtml, /function deleteSection\(index\)[\s\S]*?if \(!result\.removed\) return;\s*expandedSectionIds\.clear\(\);\s*const lastIndex = state\.sections\.length - 1;\s*const lastSection = state\.sections\[lastIndex\];\s*if \(lastSection\) expandedSectionIds\.add\(lastSection\.id\);\s*selectSection\(lastIndex\);/);
assert.doesNotMatch(indexHtml, /data-action="(?:set-active|duplicate|move-up|move-down)"|function (?:duplicateSection|moveSection)\b/);
assert.doesNotMatch(indexHtml, /delete-section-button|>×<|data-section-length|>Length<|Start = now|End = now|Start = previous section end|End = next section end|start-from-previous-end|end-from-next-end/);
assert.match(indexHtml, /const expandedSectionIds = new Set\(\);/);
assert.match(indexHtml, /function createPracticeSection\(sections, start, speed,[\s\S]*?name: ""/);
assert.match(indexHtml, /name: String\(section\.name \?\? ""\)\.slice\(0, 120\)/);
assert.doesNotMatch(indexHtml, /getNextDefaultSectionName|`Section \$\{index \+ 1\}`/);
assert.match(indexHtml, /const normalized = normalizeState\(nextState\);\s*expandedSectionIds\.clear\(\);/);
assert.match(indexHtml, /function addSectionAtPlayhead\(\)\s*{\s*const start = getAppendedSectionStart\(state\.sections, getCurrentPlayerTime\(\)\);/);
assert.match(indexHtml, /state\.sections\.push\(section\);\s*expandedSectionIds\.clear\(\);\s*expandedSectionIds\.add\(section\.id\);/);
assert.match(indexHtml, /const section = insertSectionAfter\(state\.sections, index\);\s*if \(!section\) return;\s*expandedSectionIds\.clear\(\);\s*expandedSectionIds\.add\(section\.id\);/);
assert.match(indexHtml, /if \(action === "toggle-section"\)\s*{\s*toggleSection\(index\);\s*return;/);
assert.match(indexHtml, /function toggleSection\(index\)[\s\S]*?expandedSectionIds\.delete\(section\.id\);\s*renderSections\(\);\s*return;[\s\S]*?expandedSectionIds\.clear\(\);\s*expandedSectionIds\.add\(section\.id\);\s*selectSection\(index\);\s*syncAndRender\(\);/);
assert.match(indexHtml, /const section = insertNewSectionAfter\(index\);\s*syncAndRender\(\);\s*if \(section\) scrollSectionIntoView\(section\.id\);/);
assert.match(indexHtml, /selectSection\(state\.sections\.length - 1\);\s*syncAndRender\(\);\s*scrollSectionIntoView\(section\.id\);/);
assert.match(indexHtml, /const VIDEO_STATUS_HIDE_AFTER_MS = 3000;/);
assert.match(indexHtml, /const SHARE_STATUS_HIDE_AFTER_MS = 3000;/);
assert.match(indexHtml, /function setVideoStatus\(message, kind = ""\)\s*{\s*setStatus\(elements\.videoStatus, message, kind, VIDEO_STATUS_HIDE_AFTER_MS\);/);
assert.match(indexHtml, /setVideoStatus\("Loaded state from the URL\.", "good"\);/);
assert.match(indexHtml, /setVideoStatus\("Video loaded\. Add or play a section to begin practicing\.", "good"\);/);
assert.equal((indexHtml.match(/setVideoStatus\(/g) || []).length, 7, "all six video messages plus the helper should use setVideoStatus");
assert.equal((indexHtml.match(/setStatus\(elements\.videoStatus,/g) || []).length, 1, "only setVideoStatus should call setStatus for video output");
assert.match(indexHtml, /setStatus\(elements\.shareStatus, "Share URL copied to clipboard\.", "good", SHARE_STATUS_HIDE_AFTER_MS\);/);

assert.match(indexHtml, /new ResizeObserver\(updateSectionsPanelHeight\)/);
assert.match(indexHtml, /getBoundingClientRect\(\)\.height/);
assert.match(indexHtml, /style\.setProperty\("--player-panel-height", `\$\{height}px`\)/);

assert.doesNotMatch(indexHtml, /No localStorage|sessionStorage, cookies|footer-note/);
for (const id of ["copyShareButton", "shareStatus"]) {
  assert.equal((indexHtml.match(new RegExp(`id="${id}"`, "g")) || []).length, 1, `${id} should be present exactly once`);
}

console.log("Layout and collapsible sections passed.");




